Image Management
neo4j-contrib/graphgist-portal-v3 pull request #42
Opened 2021-06-18 15:36 UTC by ficast

ACs

- User creates/updates a GraphGist Candidate with links out to images
-  Images are automatically imported (into a service like imagekit.io)
-  Links to the images are automatically replaced by links to imagekit.io (or equivalent)
-  Image nodes are created and linked to the User
-  User can see "my images" and delete images

Example use: 
- User creates a graphgist by copy+pasting some content
- User realizes an image they didn't want to share has now been uploaded to imagekit. 
- User deletes the link from the graphgist but it's still there!
- User goes to "my gallery" and deletes the image node
- User checks the link, which is now broken (as expected)

Obs:
- Sometimes when user goes to "my gallery" and deletes the image it can still be showed for a while, probably caused by some delay with imagekit service (DNS, etc). I've tested and sometimes its instantly and sometimes not.

2021-06-18 15:39 UTC, whatSocks commented on api/src/graphgists/mutations.js
> +        CREATE (i:Image $image)
🤔

2021-06-18 21:35 UTC, Masudbdqa commented
Looks good.

2021-06-18 21:36 UTC, Masudbdqa approved these changes
Looks good

2021-06-21 13:05 UTC, ficast commented
https://www.loom.com/share/22b9633114824200a453dc8dbaecae65

2021-06-24 00:07 UTC, nossila requested changes

2021-06-24 00:07 UTC, nossila commented on ui-react/src/App.js
> +        source
```suggestion
        source_url
```

revert change

2021-06-24 00:07 UTC, nossila commented on ui-react/src/App.js
> +        source
```suggestion
        source_url
```

revert change

2021-06-24 00:07 UTC, nossila commented on ui-react/src/App.js
> +        source
```suggestion
        source_url
```

revert change

2021-06-24 00:07 UTC, nossila commented on ui-react/src/candidates/CandidateCard.js
> +          source
```suggestion
        source_url
```

revert change

2021-06-24 00:07 UTC, nossila commented on ui-react/src/candidates/CandidateCard.js
> +          source
```suggestion
        source_url
```

revert change

2021-06-24 00:07 UTC, nossila commented on api/src/images/types.js
> +      return `https://${AWS_S3_BUCKET_NAME}.s3.amazonaws.com/graph_starter/images/sources/${partitions}/${size}/${source_file_name}?${source_updated_at}`;
```suggestion
    return `https://${AWS_S3_BUCKET_NAME}.s3.amazonaws.com/graph_starter/images/sources/${partitions}/${size}/${source_file_name}?${source_updated_at}`;
```

identation

2021-06-24 01:51 UTC, nossila approved these changes

2021-07-01 14:28 UTC, whatSocks commented
@ficast can you also update the readme with how to use the imagekit stuff so newcomers to the project can know how to work around it or use it

2021-07-01 14:47 UTC, whatSocks commented
<img width="908" alt="Screen Shot 2021-07-01 at 10 46 26 AM" src="https://user-images.githubusercontent.com/2731744/124144007-9748b080-da59-11eb-97a1-2d3f25f9d0c2.png">

little edge case - if I upload a .mov in the image portion of the admin edit, i get this broken image situation

<img width="666" alt="Screen Shot 2021-07-01 at 10 47 06 AM" src="https://user-images.githubusercontent.com/2731744/124144132-afb8cb00-da59-11eb-99f2-0d4a2dd6ec69.png">

for a solution could we allow only image formats in this field?

2021-07-01 18:04 UTC, whatSocks approved these changes

2021-07-01 23:50 UTC, merged